[env]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
lib_deps =
    adafruit/Adafruit BusIO@^1.14.0 
    adafruit/Adafruit GFX Library@^1.12.4
    symlink://.

[env:test]
build_src_filter = +<../examples/test/>

[env:checkerboard]
build_src_filter = +<../examples/checkerboard/>

[env:movingwords]
build_src_filter = +<../examples/movingwords/>
